### ISSUE TITLE
'PROFILE_SHEAR' not supported in Solver2Point

### ISSUE THREAD

**Issue by Christovis** [sibirrer/lenstronomy#125]
In the catalogue modelling.ipynb, the solver for constraint lens models is set to be:
`kwargs_constraints = {'solver_type': 'PROFILE_SHEAR'`}

However, when I run lenstronomy, this `solver_type` isn't supported.
The error message is as follows:
`
File "/lenstronomy/LensModel/Solver/solver2point.py", line 31, in __init__
    raise ValueError("solver_type %s is not a valid option!")
ValueError: solver_type %s is not a valid option`
`
The  only supported solvers seem to be: 'CENTER', 'ELLIPSE', 'SHAPELETS', 'THETA_E_PHI', 'THETA_E_ELLIPSE'

Is there an easy fix for this?

**Comment by sibirrer** [comment]
The reason why 'PROFILE_SHEAR' is not supported is because the specific solver has the right degrees of freedom to account for 4 image positions. If you want to constrain a lens model with two image positions, this leads to an underconstraint problem and thus you need to chose the right (2) degrees of freedom in the lens model to solve for (instead of 6). 'CENTER' choses the center_x and center_y of the main deflector, the 'ELLIPSE' the e1 and e2 ellipticity components of the main deflector and theta_e_phi choses theta_E and the direction of the ellipticity components. Depending on whether you want to set priors/constraints on some parameters, you need to pick a solver that does not solve for those parameters.

You can also disable the solver and set source_position_likelihood=True in kwargs_likelihood. This will include a punishment factor depending on how inaccurate the different image positions trace back to the same source position. The sampling however is not very efficient this way.

If this 'solves' your issue, please close it or if it evolves in a different direction, you can also close this one and open a new one.
