### ISSUE TITLE
1D Power Spectrum Calculation

### ISSUE THREAD

**Issue by amn3142** [sibirrer/lenstronomy#132]
1) I believe the formula for the power spectrum in line 22 of lenstronomy.Util.correlation should be
ps2D = (numpy.abs(F2))**2

2) In order to get a normalization from fftpack that leads to the sum of the fft amplitudes equalling the amplitudes of the input signal you have to divide by 1/N where N is the total number of points going into your fourier function.

3) I think there should be a 1/pi*(r outer edge of bin**2-rinner edge of bin**2) factor in the return from analysis_util.azimuthalAverage() function, since that is the area of an annulus. I might be misreading the code there though, but pretty sure you need the angular factor.

**Comment by sibirrer** [comment]
1. thanks for pointing this out. Effectively the function was computing a correlation function but not a power spectrum.

2. Yes! Thanks for pointing this out.
about 1&2: I added explicit definitions of the 2d power spectra that incorporate this and added test functions for the 2d case.
I was coding in the pre-release_dev branch. I don't want to merge it with the master yet as I did other changes as well that affect the running of the notebooks (basically only plotting tools).You can get this branch by:
git checkout pre-release_dev

3. the function does what it is supposed to do: providing a radial averaged function of a 2d profile. I added a test function confirming this. The question is whether this is how the 1d power spectrum is defined. I haven't looked into this. I defined a specific function of the 1d power spectrum that is calling the azimuthalAverage() function. If you have a test case for the 1d power spectrum, let me know.

Thanks a lot and let me know if you have questions about the code and/or if you have additional input!

If this is sufficient, please close the issue, otherwise leave it open. You can open this issue anytime again too.

**Comment by amn3142** [comment]
Ah ok, sorry I had misunderstood what nr was, yes, it looks good.

**Comment by sibirrer** [comment]
done with latest commit
