### ISSUE TITLE
units in tnfw profile mass_3d

### ISSUE THREAD

**Issue by amn3142** [sibirrer/lenstronomy#137]
I know I could figure this out eventually but it would be much easier if you could just answer: What are the units of mass in the function returned by mass_3d in lenstronomy/Lensmodel/Profiles/tnfw.py , function on line 161 _alpha2rho0 seems to return something unit-less unless I've missed something. 

A related question: Wondering why the lensing kwarg for the normalization is alpha_Rs since it seems like none of the functions use that, and in the conversion from rho0 to alpha_Rs the truncation is not accounted for.  Maybe that's just the tradition?

Thanks so much for your help!!!!

**Comment by sibirrer** [comment]
mass_3d in the Lens models are indeed unites (do not need an assumption of cosmology themself when otherwise used). This function is e.g. used in the Galkin.mass_profile.py routine to compute the kinematics. There you can find the function that translates the unites mass_3d to the physical units of kg * Dd* arcsec (the reasons for the additional terms is because it then performs an integral over angular units rather then physical units, but maybe I should specify this better in the future).

On the truncation and alpha_Rs convention: so the truncation is indeed not accounted in this computation and it follows the NFW convention. There is probably no analytic calculation of this quantity in TNFW and I want to keep the 'NFW analogy if not truncated' for the moment.

**Comment by amn3142** [comment]
Thanks, this is super helpful!

**Comment by sibirrer** [comment]
Great. Actually after checking the function in Galkin.mass_profile.py gives physical kg (without Dd*arcsec which is added only when performing the angular integral itself). There is a test function in test_LensModel/test_numerical_profile_integrals.py that tests the mass_3d() function numerically to recover the lensing definition of mass (the test function effectively defines the mass definition if you will). I close the issue for now.
