### ISSUE TITLE
axis ticks in the lens_model_plot() function

### ISSUE THREAD

**Issue by rkkuang** [sibirrer/lenstronomy#253]
Hi, when ploting the caustics and critical curves given a lens model,

currently the xaxis, yaxix ticks of the resulting figure seems to be incorrect in the lens_model_plot() in Plots/lens_plot.py

It can be seen when we comment out line 77 and 78, or use ax.get_xaxis().set_visible(True)

https://github.com/sibirrer/lenstronomy/blob/main/lenstronomy/Plots/lens_plot.py

**Comment by rkkuang** [comment]
Thanks for your reply @sibirrer.

For example, in the starting_guide.ipynb
http://localhost:8888/notebooks/lenstronomy_extensions/Notebooks/starting_guide.ipynb

The expected coordinates of the lens centre should be close to the given paramters:
    kwargs_sis = {'theta_E': 0.1, 'center_x': 1., 'center_y': -0.1},
and the coordinates of the lensed images (A, B, C, D) should be the results from lens equation solver:
    theta_ra, theta_dec = solver.image_position_from_source(beta_ra, beta_dec, kwargs_lens)

currently the axises resulting figure is like this (by setting axex[0].get_xaxis().set_visible(True) etc ):
![image](https://user-images.githubusercontent.com/40119865/118901816-c4784e00-b946-11eb-9539-7c5e130e6b80.png)

The convention that the vertical axis showes the DEC, the horizontal axis showes the RA (whichever direction) is fine, as long as the scale of the critical curves, and the coordinates are agree with the model.

Thanks for maintaining this package!

**Comment by sibirrer** [comment]
I see. Thanks for the illustration and explanation @rkkuang! The current routine was not meant to use the axis. I updated the routine to be consistent (also for flipped x-axis which is the way RA is defined). The reason for it is to rather match the pixel coordinate system also in case of rotated axes rather than being equivalent to the model coordinate system. But since this plotting routine currently does not offer rotated coordinate systems, it's appropriate and instructive to match the coordinate system. The recent commit should address your issue. Please close this issue if this is indeed the case or report further aspects with this particular issue. Thank you!
